/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kaixindev_kxplayer_Agent */

#ifndef _Included_com_kaixindev_kxplayer_Agent
#define _Included_com_kaixindev_kxplayer_Agent
#ifdef __cplusplus
extern "C" {
#endif
#undef com_kaixindev_kxplayer_Agent_STATE_IDLE
#define com_kaixindev_kxplayer_Agent_STATE_IDLE 0L
#undef com_kaixindev_kxplayer_Agent_STATE_OPEN
#define com_kaixindev_kxplayer_Agent_STATE_OPEN 1L
#undef com_kaixindev_kxplayer_Agent_STATE_STARTED
#define com_kaixindev_kxplayer_Agent_STATE_STARTED 2L
#undef com_kaixindev_kxplayer_Agent_STATE_RECEIVING_DATA
#define com_kaixindev_kxplayer_Agent_STATE_RECEIVING_DATA 3L
#undef com_kaixindev_kxplayer_Agent_STATE_PAUSED
#define com_kaixindev_kxplayer_Agent_STATE_PAUSED 4L
#undef com_kaixindev_kxplayer_Agent_STATE_ABORTED
#define com_kaixindev_kxplayer_Agent_STATE_ABORTED 5L

/*
 * Class:     com_kaixindev_kxplayer_Agent
 * Method:    create
 * Signature: (Lcom/kaixindev/kxplayer/Agent/Option;)Lcom/kaixindev/kxplayer/Agent;
 */
JNIEXPORT jobject JNICALL Java_com_kaixindev_kxplayer_Agent_create
  (JNIEnv *, jclass);

/*
 * Class:     com_kaixindev_kxplayer_Agent
 * Method:    open
 * Signature: (Ljava/lang/String;Lcom/kaixindev/kxplayer/AVContext;)I
 */
JNIEXPORT jint JNICALL Java_com_kaixindev_kxplayer_Agent_open
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_kaixindev_kxplayer_Agent
 * Method:    start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kaixindev_kxplayer_Agent_start
  (JNIEnv *, jobject, jobject rec_listener, jobject fin_listener);

/*
 * Class:     com_kaixindev_kxplayer_Agent
 * Method:    pause
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kaixindev_kxplayer_Agent_pause
  (JNIEnv *, jobject);

/*
 * Class:     com_kaixindev_kxplayer_Agent
 * Method:    resume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kaixindev_kxplayer_Agent_resume
  (JNIEnv *, jobject);

/*
 * Class:     com_kaixindev_kxplayer_Agent
 * Method:    abort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kaixindev_kxplayer_Agent_abort
  (JNIEnv *, jobject);

/*
 * Class:     com_kaixindev_kxplayer_Agent
 * Method:    getState
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_kaixindev_kxplayer_Agent_getState
  (JNIEnv *, jobject);
    
    
/*
 * Class:     com_kaixindev_kxplayer_Agent
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kaixindev_kxplayer_Agent_release
(JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_kaixindev_kxplayer_Agent_OnFinishListener */

#ifndef _Included_com_kaixindev_kxplayer_Agent_OnFinishListener
#define _Included_com_kaixindev_kxplayer_Agent_OnFinishListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_kaixindev_kxplayer_Agent_OnReceiveListener */

#ifndef _Included_com_kaixindev_kxplayer_Agent_OnReceiveListener
#define _Included_com_kaixindev_kxplayer_Agent_OnReceiveListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_kaixindev_kxplayer_Agent_Option */

#ifndef _Included_com_kaixindev_kxplayer_Agent_Option
#define _Included_com_kaixindev_kxplayer_Agent_Option
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
