/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kaixindev_kxplayer_JNITest */

#ifndef _Included_com_kaixindev_kxplayer_JNITest
#define _Included_com_kaixindev_kxplayer_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kaixindev_kxplayer_JNITest
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kaixindev_kxplayer_JNITest_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
