/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kaixindev_kxplayer_Device */

#ifndef _Included_com_kaixindev_kxplayer_Device
#define _Included_com_kaixindev_kxplayer_Device
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kaixindev_kxplayer_Device
 * Method:    open
 * Signature: (Lcom/kaixindev/kxplayer/Device/Option;)Lcom/kaixindev/kxplayer/Device;
 */
JNIEXPORT jobject JNICALL Java_com_kaixindev_kxplayer_Device_open
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_kaixindev_kxplayer_Device
 * Method:    pause
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_kaixindev_kxplayer_Device_pause
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_kaixindev_kxplayer_Device
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kaixindev_kxplayer_Device_close
  (JNIEnv *, jobject);

/*
 * Class:     com_kaixindev_kxplayer_Device
 * Method:    write
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_kaixindev_kxplayer_Device_write
  (JNIEnv *, jobject, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_kaixindev_kxplayer_Device_OnNoticeListener */

#ifndef _Included_com_kaixindev_kxplayer_Device_OnNoticeListener
#define _Included_com_kaixindev_kxplayer_Device_OnNoticeListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_kaixindev_kxplayer_Device_Option */

#ifndef _Included_com_kaixindev_kxplayer_Device_Option
#define _Included_com_kaixindev_kxplayer_Device_Option
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
